/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package main.java.start;

import main.java.world.Cycle;
import main.java.world.Printer;
import main.java.world.World;

public class Silvalsim extends Thread {
    
    public String getGreeting() {
        
        return "Welcome to SILVASIM.";
    }
    
    /**
     * Description: main method.
     * Builds a new thread and launches the program.
     * 
     * @author James Covert
     * @version 1.0
     */
    public static void main(String[] args) {
        
        Printer.println(new Silvalsim().getGreeting());
        
        World world = new World();
        Thread cycleThread = new Thread(new Cycle(world));
        cycleThread.setName("Cycle_Thread");
        cycleThread.start();
    }
}
