/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package test.java.start;

import static org.junit.Assert.assertNotNull;

import main.java.start.Silvalsim;

import org.junit.Test;

public class SilvalsimTest {
    @Test public void testAppHasAGreeting() {
        Silvalsim classUnderTest = new Silvalsim();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
